version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: 04:00
      timezone: Asia/Shanghai
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: 04:00
      timezone: Asia/Shanghai
